### ISSUE TITLE
stripe subscription production integration

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/ecommerce#9]
@renevatium please add details

**Comment by renevatium** [comment]
We need to upgrade the Stripe payment provider (within edX) to support recurring payments (subscription). This will require adding the relevant fields to the payment request params in the instance that a course is of mode "subscription". Stripe docs can be found [here](https://stripe.com/docs/subscriptions/quickstart)

**Comment by nicovanniekerk** [comment]
ecommerce proversity/feature-subscription-stripe-integration
edx-platform proversity/feature-ecommerce-updates

work has been staged to these two branches and on hold for a while, set on the backlog of EduNext.
